Repository OCA/vertical-rental, pull requests merged in 2022-04, with the labels that each got.

#9 [IMP] rental_base: correction to fields and method
  .pre-commit-config.yaml
  .travis.yml
  rental_base/models/sale.py
  rental_base/views/sale_view.xml
  rental_pricelist/views/product_view.xml
Labels: bot is merging ⏳

#10 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
Labels: help wanted, needs review, bot is merging ⏳

#14 [14.0][MIG] rental_offday
  rental_offday/README.rst
  rental_offday/README/CONTRIBUTORS.rst
  rental_offday/README/DESCRIPTION.rst
  rental_offday/README/HISTORY.rst
  rental_offday/README/USAGE.rst
  rental_offday/__init__.py
  rental_offday/__manifest__.py
  rental_offday/i18n/de.po
  rental_offday/i18n/rental_offday.pot
  rental_offday/models/__init__.py
  rental_offday/models/rental_offday.py
  rental_offday/models/sale.py
  rental_offday/security/ir.model.access.csv
  rental_offday/static/description/icon.png
  rental_offday/static/description/index.html
  rental_offday/tests/__init__.py
  rental_offday/tests/test_rental_offday.py
  rental_offday/views/sale_view.xml
  setup/rental_offday/odoo/addons/rental_offday
  setup/rental_offday/setup.py
Labels: approved, bot is merging ⏳

#12 [14.0][MIG] rental_pricelist_interval
  rental_pricelist_interval/README.rst
  rental_pricelist_interval/README/CONFIGURATION.rst
  rental_pricelist_interval/README/CONTRIBUTORS.rst
  rental_pricelist_interval/README/DESCRIPTION.rst
  rental_pricelist_interval/README/HISTORY.rst
  rental_pricelist_interval/README/USAGE.rst
  rental_pricelist_interval/__init__.py
  rental_pricelist_interval/__manifest__.py
  rental_pricelist_interval/data/product_pricelist_data.xml
  rental_pricelist_interval/data/product_uom_data.xml
  rental_pricelist_interval/hooks.py
  rental_pricelist_interval/i18n/de.po
  rental_pricelist_interval/i18n/rental_pricelist_interval.pot
  rental_pricelist_interval/models/__init__.py
  rental_pricelist_interval/models/product.py
  rental_pricelist_interval/models/res_company.py
  rental_pricelist_interval/models/sale.py
  rental_pricelist_interval/security/ir.model.access.csv
  rental_pricelist_interval/static/description/icon.png
  rental_pricelist_interval/static/description/index.html
  rental_pricelist_interval/tests/__init__.py
  rental_pricelist_interval/tests/test_rental_pricelist.py
  rental_pricelist_interval/views/product_pricelist_view.xml
  rental_pricelist_interval/views/product_view.xml
  rental_pricelist_interval/views/res_company_view.xml
  setup/rental_pricelist_interval/odoo/addons/rental_pricelist_interval
  setup/rental_pricelist_interval/setup.py
Labels: approved, ready to merge, bot is merging ⏳
